### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by IgorGanapolsky** [dbof10/hunt-android#6]
Hello,
when I run **script/build.sh**, I get this error:
> BUILD FAILED in 3m 1s
33 actionable tasks: 33 executed
Starting ui.home.view.HomeActivity
Starting: Intent { cmp=com.ctech.eaty/.ui.home.view.HomeActivity }
Error type 3
Error: Activity class {com.ctech.eaty/com.ctech.eaty.ui.home.view.HomeActivity} does not exist.

Please advise,
Igor

**Comment by dbof10** [comment]
Could you provide more information? I just check it out and don't see any error

**Comment by dbof10** [comment]
![screen shot 2018-01-29 at 11 40 37 am](https://user-images.githubusercontent.com/10725747/35493899-404a7a0a-04e9-11e8-9f9f-0df03f2b1da0.png)

**Comment by IgorGanapolsky** [comment]
Which version of Android Studio are you on?  I am on 3.1 Canary 7

**Comment by dbof10** [comment]
I'm still using 3.0. I'll check it out the 3.1

**Comment by dbof10** [comment]
It breaks on 3.1.0 beta1. I don't think what we can do about this.
